#!/bin/bash

[[ $- != *i* ]] && return

for file in .{extend,exports,aliases}.bashrc; do
    [[ -f ~/$file ]] && source ~/$file
done

[ -r /usr/share/bash-completion/bash_completion ] && source /usr/share/bash-completion/bash_completion

